name: dotnet package

on: [push]

jobs:
  build:
    defaults:
      run:
        working-directory: Secp256k1.Net.Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['2.1.x', '3.1.x', '5.0.x', '6.0.x']
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal --collect:"XPlat Code Coverage"

